---
width: 3
height: 2
javaFxScaling: 48
apples: 0
barrierTxtPath: "gamedata/barrier/40x20_border.txt"
aiClassNames:
- "ru.nsu.fit.smolyakov.snakegame.model.snake.ai.NotWonnaDieAISnake"
- "ru.nsu.fit.smolyakov.snakegame.model.snake.ai.StraightForwardAISnake"
speed: "LEVEL_4"
