---
width: 40
height: 20
javaFxScaling: 39
apples: 10
level: !<Random>
  density: 0.06666666666666667
aiClassNames:
- "GreedyAISnake"
- "KamikazeAISnake"
- "SamuraiAISnake"
- "StayinAliveAISnake"
speed: "fastest"
