---
width: 40
height: 20
javaFxScaling: 40
apples: 13
barrierTxtFile: "40x20_border.txt"
aiClassNames:
- "NotWonnaDieAISnake"
- "StraightForwardAISnake"
- "TotallyRandomAISnake"
- "WannaEatAISnake"
speed: "LEVEL_4"
