---
width: 40
height: 20
javaFxScaling: 42
apples: 20
barrierTxtPath: "gamedata/barrier/40x20_border.txt"
aiClassNames:
- "ru.nsu.fit.smolyakov.snakegame.model.snake.ai.NotWonnaDieAISnake"
- "ru.nsu.fit.smolyakov.snakegame.model.snake.ai.StraightForwardAISnake"
speed: "LEVEL_4"
