width: 40
height: 20
maxApples: 5
barrier: /barrier/border.txt
aiClassNames:
  - "ru.nsu.fit.smolyakov.snakegame.model.snake.ai.NotWonnaDieAISnake"
  - "ru.nsu.fit.smolyakov.snakegame.model.snake.ai.StraightForwardAISnake"
